Homepage
WildCodeSchool-2024-02/JS-Valence-P2-Lucavenger pull request #2
Opened 2024-05-13 08:29 UTC by Hasbem

Add home page

2024-05-13 08:42 UTC, Hasbem commented
a

2024-05-13 09:42 UTC, nimser requested changes
We need to keep the .gitkeep files.

2024-05-13 09:42 UTC, nimser commented on client/src/pages/.gitkeep
We need to keep this

2024-05-13 09:42 UTC, nimser commented on client/src/services/.gitkeep
Same thing, keep this file.

2024-05-13 12:56 UTC, TobniIbrahim commented
Bon mais nécessite un changement au niveau de la trop haute police d'écriture du titre , la barre doit prendre plus de place et l'image dans la barre de recherche n'est pas insérer

2024-05-13 14:27 UTC, TobniIbrahim approved these changes
Bon mais nécessite un changement au niveau de la trop haute police d'écriture du titre , la barre doit prendre plus de place et l'image dans la barre de recherche n'est pas insérer

2024-05-18 12:36 UTC, nimser commented
Last commit only adds .gitkeep in services/, not pages/

2024-05-22 09:50 UTC, closed without merging