Structuration du projet et amélioration du code du projet V1
WildCodeSchool-2024-02/JS-Valence-P2-Lucavenger pull request #4
Opened 2024-05-22 08:15 UTC by kaledguz

J'ai intégrer le routeur ainsi qu'une restructuration du projet pour la continuité du projet dans le futur. J'ai ajouter aussi un composant de chargement de page  et une amélioration du code du projet v1.

2024-05-22 08:19 UTC, Hasbem commented
Il faut encore modifier la mise en page de la description, changer la couleur et agrandir le h1, et changer également la couleur du nom du personnage sélectionné

2024-05-22 09:03 UTC, Hasbem requested changes
Il faut encore modifier la mise en page de la description, changer la couleur et agrandir le h1, et changer également la couleur du nom du personnage sélectionné

2024-05-22 09:54 UTC, Hasbem approved these changes

2024-05-22 10:14 UTC, Hasbem approved these changes

2024-05-22 10:26 UTC, nimser requested changes

2024-05-22 10:26 UTC, nimser commented on client/src/components/Comics.jsx
> +    const privateKey = "c09e9c38566391defe2a6c0f74386a57a394e501";
Don't include private credentials on Github. Use a `.env` file. See the vite documentation: https://vitejs.dev/guide/env-and-mode#env-files

2024-05-22 10:26 UTC, nimser commented on client/src/App.jsx
> +    <Router>
Please migrate to react-router-v6, this is the old API https://reactrouter.com/en/main/upgrading/v6-data#migrating-to-routerprovider

2024-05-22 10:26 UTC, nimser commented on client/src/main.jsx
This file was using the newer createBrowserRouter API. You should revert your changes on this file.

2024-05-22 10:26 UTC, nimser commented on client/src/pages/CharacterDetailPage.jsx
> +        const PRIVATE_KEY = "f04d78d769814078851b5f2a176e86c3ab919ad6";
Same thing, use `.env`

2024-05-22 10:26 UTC, nimser commented on client/src/services/Api.js
> +const PRIVATE_KEY = "f04d78d769814078851b5f2a176e86c3ab919ad6";
use `.env`

2024-05-23 08:50 UTC, nimser approved these changes
Good work. Added environment variables.

2024-05-23 08:51 UTC, merged